name:                scotty-bytestring
version:             0.1.0.0
github:              srdqty/scotty-bytestring
license:             BSD3
author:              Sofia Donataccio
maintainer:          srdqty@gmail.com
copyright:           Copyright (c) 2018 Sofia Donataccio

extra-source-files:
  - README.md
  - ChangeLog.md

synopsis: ByteString versions of some Scotty functions.
description: >
  ByteString versions of some Scotty functions. The main purpose is to avoid
  re-decoding and/or re-encoding data when reading and setting headers. It's
  meant as an alternative for some of the functions that automatically decode
  to Text.
category:            Web

dependencies:
  - base >= 4.7 && < 5
  - bytestring >= 0.10.02 && < 0.11
  - case-insensitive >= 1.0.0.1 && < 1.3
  - http-types >= 0.8.2 && < 0.13
  - mtl >= 2.1.2 && < 2.3
  - scotty >= 0.11.2 && < 0.12
  - wai >= 3.0.0 && < 3.3

library:
  source-dirs: src
  ghc-options:
    - -Wall
    - -O2

tests:
  scotty-bytestring-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wall
      - -O2
    dependencies:
      - scotty-bytestring
      - hspec == 2.*
      - hspec-wai >= 0.6.3
      - text >= 0.11.3.1 && < 1.3
